### ISSUE TITLE
server.properties

### ISSUE THREAD

**Issue by AmandaJonesAway** [TrueOsiris/docker-minecraft-skyfactory4#9]
start.sh does
`cp -rf /tmp/feed-the-beast/* .
echo "eula=true" > eula.txt

if [[ ! -e server.properties ]]; then
    cp /tmp/server.properties .
`
which I assume is an intent not to overwrite server.properties if it already exists.  However, /tmp/feed-the-beast ends up with a default server.properties in it, thus any existing one always gets overwritten anywya.

**Comment by bitjumper1** [comment]
My son and I verified this. He was trying to modify server.properties but it wouldn't take. While triaging, we found this issue posted here. We deduced that after our container has been created, we can go into our container's CLI and remove /tmp/feed-the-beast/server.properties. Now my son is happy! Yay!

We are running on a Mac using Docker Desktop. We used docker-compose to create our container. I'd sit down and come up with a solution to this issue, but I'm rather new to docker and not 100% sure on container creation and start process yet.

**Comment by msshnl** [comment]
I want to add to this indeed.

On every container launch the server.properties seems to get updated to a standard one taking into account what is set in the env variables.

What this does... It also overwrites my whitelist settings for instance.

A improvement I believe would be: generate a server.properties if there is none but if there is one don't do anything and assume the owner know what he was doing.

**Comment by msshnl** [comment]
Figured out the bug for you:

cp -rf /tmp/feed-the-beast/* .
echo "eula=true" > eula.txt

if [[ ! -e server.properties ]]; then
    cp /tmp/server.properties .
fi

In the first part you copy the full feed-the-beast map:
![image](https://user-images.githubusercontent.com/18720592/115511162-d8199180-a280-11eb-9c7a-1f24ac0fe1c6.png)
and by default that contains a server.properties file so everything gets lost....

Remove that from the image and fully fixed.

**Comment by TrueOsiris** [comment]
my bad. Sorry about this late response.
I build in an extra check. If the copy has already been done, it will not reoccur. Hence, you can adapt the server.properties file properly.
